DROP TABLE IF EXISTS FLIGHT;

CREATE TABLE FLIGHT (
  ITINERARY_ID VARCHAR PRIMARY KEY,
  DEPARTURE_DATE DATE NOT NULL,
  ARRIVAL_DATE DATE NOT NULL,
  ORIGIN_CITY VARCHAR(250) NOT NULL,
  DESTINATION_CITY VARCHAR(250) NOT NULL,
  PASSENGER_NAME VARCHAR(250) NOT NULL,
  PASSENGER_AGE INT NOT NULL,
  LUGGAGE_HOLD BOOLEAN NOT NULL,
  PRICE DECIMAL(6,2) NOT NULL,
  DEPARTURE_TIME TIME NOT NULL,
  ARRIVAL_TIME TIME NOT NULL
);

INSERT INTO FLIGHT (
	ITINERARY_ID, 
	DEPARTURE_DATE, 
	ARRIVAL_DATE, 
	ORIGIN_CITY, 
	DESTINATION_CITY, 
	PASSENGER_NAME,
	PASSENGER_AGE,
	LUGGAGE_HOLD,
	PRICE,
	DEPARTURE_TIME,
	ARRIVAL_TIME)
VALUES (
	'123e4567-e89b-12d3-a456-556642440000',
	'2021-01-01',
	'2021-01-02',
	'Mexico City',
	'Barcelona',
	'Gabriel Garcia',
	30,
	false,
	3800.50,
	'15:50:03',
	'05:47:23'
);